[project]
name = "misanthrope-pm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.124.0",
    "rich>=14.2.0",
    "sqlmodel>=0.0.27",
    "typer[all]>=0.20.0",
]
